version: '3'

services:
  php:
    container_name: svs_php
    environment:
      TZ: Asia/Tokyo
    build: ./docker/php
    volumes:
    - ./src:/var/www

  nginx:
    image: nginx
    container_name: svs_nginx
    environment:
      TZ: Asia/Tokyo
    ports:
    - 80:80
    volumes:
    - ./src:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    environment:
      TZ: Asia/Tokyo
    image: mysql:5.7
    container_name: svs_mysql
    environment:
      MYSQL_ROOT_PASSWORD: svs_root
      MYSQL_DATABASE: svs_db
      MYSQL_USER: svs
      MYSQL_PASSWORD: svs
      TZ: 'Asia/Tokyo'
    command: '--innodb_use_native_aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    volumes:
    - ./docker/db/data:/var/lib/mysql:cached
    ports:
    - 3306:3306